select deptno as dept_no, count(*) as no_of_emp, avg(salary) as avg_salary, max(salary) as max_salary from employee where empname like '%A%' group by deptno having count(*) >= 2;
select deptno, count(*) as no_of_emp, avg(salary) as avg_salary from employee where job like '%MANAGER%' and salary > 40000 group by deptno;
select to_char(hire_date,'YYYY') as year_of_joining, count(*) as no_of_emp, sum(salary) as total_salary, avg(salary) as avg_salary from employee group by to_char(hire_date,'YYYY') having count(*) > 2;
select deptno, count(*) as no_of_emp, avg(salary) as avg_salary from employee where to_char(hire_date,'MM') = '06' group by deptno having count(*) >= 2;
select job, count(*) as no_of_emp, avg(salary) as avg_salary from employee where empname like 'S%' group by job having count(*) > 1;
select deptno, count(*) as no_of_emp, avg(salary) as avg_salary from employee where dob > to_date('01-01-1990','DD-MM-YYYY') group by deptno having count(*) >= 2;
select to_char(dob,'YYYY') as year_of_birth, count(*) as no_of_emp, max(salary) as max_salary, min(salary) as min_salary from employee where empname like '%A' group by to_char(dob,'YYYY') having count(*) >= 2;
select deptno, sum(salary) as total_salary, avg(salary) as avg_salary, count(*) as emp_count from employee where job like 'A%' group by deptno having sum(salary) > 100000;
select to_char(hire_date,'MM') as hire_month, count(*) as no_of_emp, avg(salary) as avg_salary from employee group by to_char(hire_date,'MM') having count(*) >= 2;
select deptno, gender, count(*) as emp_count, avg(salary) as avg_salary from employee where empname like '%AN%' group by deptno, gender having count(*) >= 2;
select job, to_char(hire_date,'YYYY') as year_of_joining, count(*) as no_of_emp, avg(salary) as avg_salary from employee where hire_date > to_date('01-01-2015','DD-MM-YYYY') group by job, to_char(hire_date,'YYYY') having count(*) >= 2;
select deptno, count(*) as no_of_emp, avg(salary) as avg_salary from employee where length(empname) > 5 group by deptno having avg(salary) > 30000;
select to_char(hire_date,'YYYY') as year_of_joining, count(*) as emp_count, sum(bonus) as total_bonus, avg(bonus) as avg_bonus from employee where job like '%E%' group by to_char(hire_date,'YYYY') having count(*) > 2;
select deptno, count(*) as no_of_emp, max(salary) as max_salary, min(salary) as min_salary from employee where empname like 'A%' or empname like 'M%' group by deptno having count(*) >= 2;
select job, count(*) as no_of_emp, avg(salary) as avg_salary, avg(comm) as avg_commission from employee where hire_date < to_date('01-01-2015','DD-MM-YYYY') group by job having count(*) > 2 and avg(salary) > 25000;
select deptno, to_char(hire_date,'YYYY') as year_of_joining, count(*) as no_of_emp, avg(salary) as avg_salary from employee where empname like '%R%' and hire_date > to_date('01-01-2014','DD-MM-YYYY') group by deptno, to_char(hire_date,'YYYY') having count(*) >= 2;
select deptno, count(*) as emp_count, avg(salary) as avg_salary, avg(bonus) as avg_bonus from employee where to_char(dob,'MM') = '01' group by deptno having count(*) >= 2 and avg(salary) > 30000;
select job, count(*) as no_of_emp, sum(salary) as total_salary, avg(salary) as avg_salary from employee where empname like 'A%' or empname like 'E%' or empname like 'I%' or empname like 'O%' or empname like 'U%' group by job having count(*) >= 2 and sum(salary) > 75000;
select deptno, count(*) as no_of_emp, avg(salary) as avg_salary, max(salary) as max_salary from employee where months_between(to_date('01-01-2025','DD-MM-YYYY'), hire_date) > 120 group by deptno having count(*) >= 2;
select deptno, job, gender, count(*) as no_of_emp, avg(salary) as avg_salary, sum(bonus) as total_bonus from employee where empname like '%A%' and hire_date > to_date('01-01-2010','DD-MM-YYYY') and (job like 'A%' or job like 'M%') group by deptno, job, gender having count(*) >= 2 and avg(salary) > 30000;
