BEGIN
    FOR t IN (
        SELECT column_value AS table_name
        FROM TABLE(SYS.ODCIVARCHAR2LIST(
            'PARTICIPATION','EVENT_REGISTRATION','EVENT','RESULT',
            'ENROLLMENT','COURSE','FACULTY','STUDENT','DEPARTMENT',
            'HIGH_CGPA_STUDENTS'
        ))
    ) LOOP
        FOR tab IN (
            SELECT table_name FROM user_tables
            WHERE table_name = t.table_name
        ) LOOP
            EXECUTE IMMEDIATE
                'DROP TABLE ' || tab.table_name || ' CASCADE CONSTRAINTS PURGE';
        END LOOP;
    END LOOP;
END;
/

CREATE TABLE DEPARTMENT (
    DEPT_ID          CHAR(3) PRIMARY KEY,
    DEPT_NAME        VARCHAR2(50) NOT NULL,
    HOD_NAME         VARCHAR2(50),
    OFFICE_LOCATION  VARCHAR2(50),
    CONTACT_NO       VARCHAR2(10)
);
CREATE TABLE STUDENT (
    STUDENT_ID      CHAR(4) PRIMARY KEY,
    STUDENT_NAME    VARCHAR2(50) NOT NULL,
    DOB             DATE,
    GENDER          CHAR(1),
    MOBILE_NO       VARCHAR2(10),
    EMAIL_ID        VARCHAR2(50),
    DEPT_ID         CHAR(3),
    ADMISSION_DATE  DATE,
    CGPA            NUMBER(3,2),
    CONSTRAINT FK_STUDENT_DEPT
    FOREIGN KEY (DEPT_ID)
    REFERENCES DEPARTMENT(DEPT_ID)
);
CREATE TABLE FACULTY (
    FACULTY_ID      CHAR(4) PRIMARY KEY,
    FACULTY_NAME    VARCHAR2(50),
    QUALIFICATION   VARCHAR2(30),
    DESIGNATION     VARCHAR2(40),
    JOINING_DATE    DATE,
    SALARY          NUMBER(8,2),
    EMAIL_ID        VARCHAR2(50),
    DEPT_ID         CHAR(3),
    CONSTRAINT FK_FACULTY_DEPT
    FOREIGN KEY (DEPT_ID)
    REFERENCES DEPARTMENT(DEPT_ID)
);
CREATE TABLE COURSE (
    COURSE_ID      CHAR(4) PRIMARY KEY,
    COURSE_NAME    VARCHAR2(100),
    CREDITS        NUMBER(2),
    SEMESTER       NUMBER(2)
);
CREATE TABLE ENROLLMENT (
    ENROLLMENT_ID    CHAR(5) PRIMARY KEY,
    STUDENT_ID       CHAR(4),
    COURSE_ID        CHAR(4),
    ENROLLMENT_DATE  DATE DEFAULT SYSDATE,
    CONSTRAINT FK_ENROLL_STUDENT
    FOREIGN KEY (STUDENT_ID)
    REFERENCES STUDENT(STUDENT_ID),
    CONSTRAINT FK_ENROLL_COURSE
    FOREIGN KEY (COURSE_ID)
    REFERENCES COURSE(COURSE_ID)
);
CREATE TABLE RESULT (
    RESULT_ID        CHAR(4) PRIMARY KEY,
    STUDENT_ID       CHAR(4),
    COURSE_ID        CHAR(4),
    INTERNAL_MARKS   NUMBER(3),
    EXTERNAL_MARKS   NUMBER(3),
    TOTAL_MARKS      NUMBER(3),
    CONSTRAINT FK_RESULT_STUDENT
    FOREIGN KEY (STUDENT_ID)
    REFERENCES STUDENT(STUDENT_ID),
    CONSTRAINT FK_RESULT_COURSE
    FOREIGN KEY (COURSE_ID)
    REFERENCES COURSE(COURSE_ID)
);
CREATE TABLE EVENT (
    EVENT_ID      CHAR(4) PRIMARY KEY,
    EVENT_NAME    VARCHAR2(50),
    EVENT_DATE    DATE,
    VENUE         VARCHAR2(50)
);
CREATE TABLE EVENT_REGISTRATION (
    REGISTRATION_ID    CHAR(5) PRIMARY KEY,
    STUDENT_ID         CHAR(4),
    EVENT_ID           CHAR(4),
    REGISTRATION_DATE  DATE DEFAULT SYSDATE,
    CONSTRAINT FK_EVENTREG_STUDENT
    FOREIGN KEY (STUDENT_ID)
    REFERENCES STUDENT(STUDENT_ID),
    CONSTRAINT FK_EVENTREG_EVENT
    FOREIGN KEY (EVENT_ID)
    REFERENCES EVENT(EVENT_ID)
);

CREATE TABLE PARTICIPATION (
    PARTICIPATION_ID     CHAR(5) PRIMARY KEY,
    STUDENT_ID            CHAR(4),
    EVENT_ID               CHAR(4),
    PARTICIPATION_STATUS   VARCHAR2(20),
    CONSTRAINT FK_PARTICIPATION_STUDENT
    FOREIGN KEY (STUDENT_ID)
    REFERENCES STUDENT(STUDENT_ID),
    CONSTRAINT FK_PARTICIPATION_EVENT
    FOREIGN KEY (EVENT_ID)
    REFERENCES EVENT(EVENT_ID)
);

INSERT INTO DEPARTMENT
VALUES ('D01', 'Computer Science', 'Dr. Anil Kumar', 'Carmel Block', '9876543210');
INSERT INTO DEPARTMENT
(DEPT_ID, DEPT_NAME, OFFICE_LOCATION)
VALUES ('D02', 'Electronics', 'Main Block');
INSERT INTO DEPARTMENT
VALUES ('D03', 'Mechanical', 'Dr. Rajesh', 'North Block', '9876500001');
INSERT INTO DEPARTMENT
VALUES ('D04', 'Civil', 'Dr. Priya', 'South Block', '9876500002');
INSERT INTO DEPARTMENT
VALUES ('D05', 'Commerce', 'Dr. Mathew', 'Commerce Block', '9876500003');

INSERT INTO STUDENT
(STUDENT_ID, STUDENT_NAME, DOB, GENDER, MOBILE_NO,
 EMAIL_ID, DEPT_ID, ADMISSION_DATE, CGPA)
VALUES
('S101', 'Akhil Raj', TO_DATE('15-08-2005','DD-MM-YYYY'), 'M',
 '9876501234', 'akhil@gmail.com', 'D01', SYSDATE, 8.2);

INSERT INTO STUDENT
(STUDENT_ID, STUDENT_NAME, DOB, GENDER, MOBILE_NO,
 EMAIL_ID, DEPT_ID, ADMISSION_DATE)
VALUES
('S102', 'Nithin Das', TO_DATE('20-01-2005','DD-MM-YYYY'), 'M',
 '9876545678', 'nithin@gmail.com', 'D01', SYSDATE);

INSERT INTO STUDENT
(STUDENT_ID, STUDENT_NAME, DOB, GENDER, MOBILE_NO,
 EMAIL_ID, DEPT_ID, ADMISSION_DATE, CGPA)
VALUES
('S103', 'Anjana Nair', TO_DATE('10-09-2005','DD-MM-YYYY'), 'F',
 '9876512345', 'anjana@gmail.com', 'D01', SYSDATE, 9.4);

INSERT ALL
  INTO FACULTY
  VALUES ('F102', 'Arun Kumar', 'M.Tech', 'Assistant Professor',
          TO_DATE('15-07-2023','DD-MM-YYYY'), 50000, 'arun@rajagiri.edu', 'D01')
  INTO FACULTY
  VALUES ('F103', 'Divya Thomas', 'PhD', 'Professor',
          TO_DATE('20-01-2021','DD-MM-YYYY'), 70000, 'divya@rajagiri.edu', 'D02')
SELECT * FROM DUAL;

INSERT INTO FACULTY
VALUES
('F101', 'Meera Joseph', 'PhD', 'Assistant Professor',
 TO_DATE('01-06-2022','DD-MM-YYYY'), 55000, 'meera@rajagiri.edu', 'D01');

INSERT INTO COURSE
(COURSE_ID, COURSE_NAME, CREDITS, SEMESTER)
VALUES
('C101', 'Database Management Systems', 4, 3);

INSERT INTO COURSE
VALUES
('C102', 'Operating Systems', 4, 3);

INSERT INTO ENROLLMENT
(ENROLLMENT_ID, STUDENT_ID, COURSE_ID)
VALUES
('EN101', 'S101', 'C101');

INSERT INTO RESULT
(RESULT_ID, STUDENT_ID, COURSE_ID,
 INTERNAL_MARKS, EXTERNAL_MARKS, TOTAL_MARKS)
VALUES
('R101', 'S101', 'C101', 25, 65, 25 + 65);

INSERT ALL
  INTO EVENT
  VALUES ('E101', 'Tech Fest', TO_DATE('15-09-2026','DD-MM-YYYY'), 'Auditorium')
  INTO EVENT
  VALUES ('E102', 'Sports Meet', TO_DATE('20-10-2026','DD-MM-YYYY'), 'College Ground')
  INTO EVENT
  VALUES ('E103', 'Cultural Fest', TO_DATE('10-11-2026','DD-MM-YYYY'), 'Open Stage')
SELECT * FROM DUAL;

INSERT INTO EVENT_REGISTRATION
(REGISTRATION_ID, STUDENT_ID, EVENT_ID)
VALUES
('R1001', 'S101', 'E101');

INSERT INTO PARTICIPATION
(PARTICIPATION_ID, STUDENT_ID, EVENT_ID, PARTICIPATION_STATUS)
VALUES
('P1001', 'S101', 'E101', 'REGISTERED');

CREATE TABLE HIGH_CGPA_STUDENTS AS
SELECT *
FROM STUDENT
WHERE 1 = 0;

INSERT INTO HIGH_CGPA_STUDENTS
SELECT *
FROM STUDENT
WHERE CGPA >= 8;

COMMIT;

desc high_cgpa_students
desc EVENT_REGISTRATION
desc EVENT
desc RESULT
desc ENROLLMENT
desc COURSE
desc FACULTY
desc STUDENT
desc DEPARTMENT
select * from DEPARTMENT;
select * from STUDENT;
select * from FACULTY;
select * from COURSE;
select * from ENROLLMENT;
select * from RESULT;
select * from EVENT;
select * from EVENT_REGISTRATION;
select * from high_cgpa_students;

UPDATE STUDENT
SET CGPA = 8.7
WHERE STUDENT_ID = 'S101';

SELECT * FROM STUDENT
WHERE STUDENT_ID = 'S101';

UPDATE STUDENT
SET MOBILE_NO = '9876543210',
    EMAIL_ID = 'student101@gmail.com'
WHERE STUDENT_ID = 'S101';

SELECT * FROM STUDENT
WHERE STUDENT_ID = 'S101';

UPDATE FACULTY
SET SALARY = SALARY + 5000
WHERE FACULTY_ID = 'F101';

SELECT * FROM FACULTY
WHERE FACULTY_ID = 'F101';

UPDATE FACULTY
SET SALARY = SALARY * 1.10;

SELECT * FROM FACULTY;

SET SALARY = SALARY * 1.08
WHERE DESIGNATION = 'Assistant Professor';

SELECT * FROM FACULTY
WHERE DESIGNATION = 'Assistant Professor';

UPDATE DEPARTMENT
SET OFFICE_LOCATION = 'Golden Aureole Block'
WHERE DEPT_NAME = 'Computer Science';

SELECT * FROM DEPARTMENT
WHERE DEPT_NAME = 'Computer Science';

UPDATE COURSE
SET CREDITS = 5
WHERE COURSE_NAME = 'Database Management Systems';

SELECT * FROM COURSE
WHERE COURSE_NAME = 'Database Management Systems';

ALTER TABLE COURSE ADD FACULTY_ID CHAR(4);
ALTER TABLE COURSE ADD CONSTRAINT FK_COURSE_FACULTY
    FOREIGN KEY (FACULTY_ID) REFERENCES FACULTY(FACULTY_ID);

UPDATE COURSE SET FACULTY_ID = 'F101' WHERE COURSE_ID = 'C101';

UPDATE COURSE
SET FACULTY_ID = 'F102'
WHERE FACULTY_ID = 'F101';

SELECT * FROM COURSE
WHERE FACULTY_ID = 'F102';

UPDATE RESULT
SET TOTAL_MARKS = INTERNAL_MARKS + EXTERNAL_MARKS;

SELECT * FROM RESULT;

ALTER TABLE RESULT ADD GRADE CHAR(1);

UPDATE RESULT
SET GRADE = 'A'
WHERE TOTAL_MARKS >= 80;

SELECT * FROM RESULT
WHERE GRADE = 'A';

ALTER TABLE RESULT ADD RESULT_STATUS VARCHAR2(10);

UPDATE RESULT
SET RESULT_STATUS =
CASE
    WHEN TOTAL_MARKS >= 50 THEN 'PASS'
    ELSE 'FAIL'
END;

SELECT * FROM RESULT;

UPDATE PARTICIPATION
SET PARTICIPATION_STATUS = 'ATTENDED'
WHERE STUDENT_ID = 'S101'
  AND EVENT_ID = 'E101';

SELECT * FROM PARTICIPATION
WHERE STUDENT_ID = 'S101'
  AND EVENT_ID = 'E101';

ALTER TABLE EVENT ADD REGISTRATION_FEE NUMBER(8,2);

UPDATE EVENT
SET REGISTRATION_FEE = 0
WHERE REGISTRATION_FEE IS NULL;

SELECT * FROM EVENT;

ALTER TABLE EVENT ADD MAX_PARTICIPANTS NUMBER(5);

UPDATE EVENT SET MAX_PARTICIPANTS = 150 WHERE EVENT_ID = 'E102';

UPDATE EVENT
SET REGISTRATION_FEE = REGISTRATION_FEE * 1.15
WHERE MAX_PARTICIPANTS > 100;

SELECT * FROM EVENT
WHERE MAX_PARTICIPANTS > 100;

ALTER TABLE ENROLLMENT ADD ACADEMIC_YEAR VARCHAR2(9);
-- seed a value so the update below has something to change
UPDATE ENROLLMENT SET ACADEMIC_YEAR = '2025-2026' WHERE ENROLLMENT_ID = 'EN101';

UPDATE ENROLLMENT
SET ACADEMIC_YEAR = '2026-2027'
WHERE ACADEMIC_YEAR = '2025-2026';

SELECT * FROM ENROLLMENT;

ALTER TABLE STUDENT
ADD ADDRESS VARCHAR2(200);

DESC STUDENT;

ALTER TABLE STUDENT
ADD (
    CITY VARCHAR2(50),
    STATE VARCHAR2(50)
);

DESC STUDENT;

ALTER TABLE FACULTY
ADD EXPERIENCE_YEARS NUMBER(2);

DESC FACULTY;

ALTER TABLE STUDENT
MODIFY STUDENT_NAME VARCHAR2(100);

DESC STUDENT;

ALTER TABLE STUDENT
MODIFY MOBILE_NO VARCHAR2(15);

DESC STUDENT;

ALTER TABLE STUDENT
RENAME COLUMN MOBILE_NO TO CONTACT_NUMBER;

DESC STUDENT;

ALTER TABLE COURSE
RENAME COLUMN COURSE_NAME TO COURSE_TITLE;

DESC COURSE;

ALTER TABLE STUDENT
DROP COLUMN ADDRESS;

DESC STUDENT;

ALTER TABLE FACULTY
DROP COLUMN QUALIFICATION;

DESC FACULTY;

ADD CONSTRAINT CHK_FACULTY_SALARY
CHECK (SALARY > 0);

DESC FACULTY;

ALTER TABLE STUDENT
ADD CONSTRAINT CHK_STUDENT_CGPA
CHECK (CGPA BETWEEN 0 AND 10);

DESC STUDENT;

ALTER TABLE EVENT
MODIFY EVENT_NAME VARCHAR2(100) NOT NULL;

DESC EVENT;

ALTER TABLE STUDENT
ADD CONSTRAINT UK_CONTACT_NUMBER
UNIQUE (CONTACT_NUMBER);

DESC STUDENT;

RENAME EVENT TO COLLEGE_EVENT;

DESC COLLEGE_EVENT;

RENAME COLLEGE_EVENT TO EVENT;

DESC EVENT;

ALTER TABLE DEPARTMENT
ADD HOD_FACULTY_ID CHAR(4);

DESC DEPARTMENT;

ALTER TABLE DEPARTMENT
ADD CONSTRAINT FK_DEPT_HOD
FOREIGN KEY (HOD_FACULTY_ID)
REFERENCES FACULTY(FACULTY_ID);

DESC DEPARTMENT;


-- 48. Drop HOD_NAME column
ALTER TABLE DEPARTMENT
DROP COLUMN HOD_NAME;

DESC DEPARTMENT;


ALTER TABLE COURSE
DISABLE CONSTRAINT FK_COURSE_FACULTY;

ALTER TABLE COURSE
ENABLE CONSTRAINT FK_COURSE_FACULTY;

SELECT * FROM DEPARTMENT;

SELECT * FROM STUDENT;

SELECT * FROM FACULTY;

SELECT * FROM COURSE;

SELECT * FROM ENROLLMENT;

SELECT STUDENT_ID, STUDENT_NAME, GENDER, CGPA
FROM STUDENT;

SELECT FACULTY_ID, FACULTY_NAME, DESIGNATION, SALARY
FROM FACULTY;

SELECT COURSE_ID, COURSE_TITLE, CREDITS, SEMESTER
FROM COURSE;

SELECT EVENT_NAME, EVENT_DATE, VENUE, REGISTRATION_FEE
FROM EVENT;

SELECT RESULT_ID, INTERNAL_MARKS, EXTERNAL_MARKS, TOTAL_MARKS, GRADE, RESULT_STATUS
FROM RESULT;

SELECT DISTINCT DESIGNATION
FROM FACULTY;

SELECT DISTINCT QUALIFICATION
FROM FACULTY;

SELECT DISTINCT SEMESTER
FROM COURSE;

SELECT STUDENT_NAME AS Student_Name, CGPA AS Grade_Point_Average
FROM STUDENT;

SELECT FACULTY_NAME, SALARY AS MONTHLY_SALARY, SALARY * 12 AS ANNUAL_SALARY
FROM FACULTY;

SELECT FACULTY_NAME, SALARY AS CURRENT_SALARY, SALARY * 1.10 AS SALARY_AFTER_INCREASE
FROM FACULTY;

SELECT RESULT_ID, INTERNAL_MARKS, EXTERNAL_MARKS,
       (INTERNAL_MARKS + EXTERNAL_MARKS) AS CALCULATED_TOTAL
FROM RESULT;

SELECT EVENT_NAME, REGISTRATION_FEE, REGISTRATION_FEE * 1.18 AS FEE_WITH_TAX
FROM EVENT;

SELECT * FROM STUDENT WHERE GENDER = 'F';

SELECT * FROM STUDENT WHERE CGPA > 8;

SELECT * FROM STUDENT WHERE CGPA <= 6;

SELECT * FROM STUDENT WHERE DEPT_ID = 'D01';

SELECT * FROM FACULTY WHERE SALARY > 50000;

SELECT * FROM FACULTY WHERE DESIGNATION = 'Assistant Professor';

SELECT * FROM FACULTY WHERE QUALIFICATION = 'PhD';

SELECT * FROM COURSE WHERE SEMESTER = 3;

SELECT * FROM COURSE WHERE CREDITS > 4;

SELECT * FROM RESULT WHERE RESULT_STATUS = 'PASS';

SELECT * FROM RESULT WHERE TOTAL_MARKS >= 80;

SELECT * FROM RESULT WHERE INTERNAL_MARKS > EXTERNAL_MARKS;

SELECT * FROM EVENT WHERE REGISTRATION_FEE > 500;

SELECT * FROM EVENT WHERE MAX_PARTICIPANTS > 100;

SELECT * FROM PARTICIPATION WHERE PARTICIPATION_STATUS = 'ATTENDED';

SELECT * FROM STUDENT WHERE GENDER = 'F' AND CGPA > 8;

SELECT * FROM STUDENT WHERE CGPA BETWEEN 7 AND 9;

SELECT * FROM FACULTY WHERE DESIGNATION = 'Assistant Professor' AND SALARY > 45000;

SELECT * FROM FACULTY WHERE QUALIFICATION IN ('PhD', 'MPhil');

SELECT * FROM FACULTY WHERE SALARY BETWEEN 40000 AND 70000;

SELECT * FROM COURSE WHERE SEMESTER IN (1, 3, 5);

SELECT * FROM COURSE WHERE SEMESTER NOT IN (7, 8);

SELECT * FROM RESULT WHERE GRADE IN ('A', 'B', 'C');

SELECT * FROM EVENT WHERE REGISTRATION_FEE BETWEEN 100 AND 1000;

SELECT * FROM STUDENT WHERE STUDENT_NAME LIKE 'A%';

SELECT * FROM STUDENT WHERE STUDENT_NAME LIKE '%Raj%';

SELECT * FROM FACULTY WHERE EMAIL_ID LIKE '%@rajagiri.edu';

SELECT * FROM COURSE WHERE COURSE_TITLE LIKE '%Database%';

SELECT * FROM DEPARTMENT WHERE DEPT_NAME LIKE '%Science%';

SELECT * FROM STUDENT WHERE CGPA IS NULL;

SELECT * FROM COURSE WHERE FACULTY_ID IS NULL;

SELECT * FROM STUDENT ORDER BY STUDENT_NAME ASC;

SELECT * FROM STUDENT ORDER BY CGPA DESC;

SELECT * FROM FACULTY ORDER BY SALARY DESC;

SELECT * FROM COURSE ORDER BY SEMESTER ASC, CREDITS DESC;

SELECT UPPER(STUDENT_NAME) AS STUDENT_NAME_UPPER
FROM STUDENT;

SELECT INITCAP(FACULTY_NAME) AS FACULTY_NAME_FORMATTED
FROM FACULTY;

SELECT STUDENT_NAME, LENGTH(STUDENT_NAME) AS NAME_LENGTH
FROM STUDENT;

SELECT STUDENT_NAME, ROUND(CGPA, 1) AS CGPA_ROUNDED
FROM STUDENT;

SELECT FACULTY_NAME, EXTRACT(YEAR FROM JOINING_DATE) AS JOINING_YEAR
FROM FACULTY;

SELECT COUNT(*) AS TOTAL_STUDENTS
FROM STUDENT;

SELECT MAX(CGPA) AS HIGHEST_CGPA,
       MIN(CGPA) AS LOWEST_CGPA,
       AVG(CGPA) AS AVERAGE_CGPA
FROM STUDENT;
